import { Brand, POI, Location } from '@/types';

// Toronto downtown coordinates
const TORONTO_CENTER: Location = {
  lat: 43.6532,
  lng: -79.3832,
};

export const dummyBrands: Brand[] = [
  {
    id: '1',
    name: 'Adidas',
    logo: 'adidas',
    location: { lat: 43.6540, lng: -79.3840 },
    distance: 0.5,
    openingHours: "Open 'til 6pm",
    isOpen: true,
    waitTime: 100,
    capacity: 100,
  },
  {
    id: '2',
    name: 'Nike',
    logo: 'nike',
    location: { lat: 43.6525, lng: -79.3815 },
    distance: 0.7,
    openingHours: "Open 'til 8pm",
    isOpen: true,
    waitTime: 15,
    capacity: 15,
  },
  {
    id: '3',
    name: 'Puma',
    logo: 'puma',
    location: { lat: 43.6510, lng: -79.3855 },
    distance: 0.9,
    openingHours: "Open 'til 7pm",
    isOpen: true,
    waitTime: 100,
    capacity: 100,
  },
  {
    id: '4',
    name: 'Under Armour',
    logo: 'under-armour',
    location: { lat: 43.6500, lng: -79.3820 },
    distance: 1.2,
    openingHours: "Open 'til 6pm",
    isOpen: true,
    waitTime: 80,
    capacity: 80,
  },
  {
    id: '5',
    name: 'Timberland',
    logo: 'timberland',
    location: { lat: 43.6495, lng: -79.3835 },
    distance: 1.3,
    openingHours: "Open 'til 6pm",
    isOpen: true,
    waitTime: 80,
    capacity: 80,
  },
  {
    id: '6',
    name: 'EA7 Emporio Armani',
    logo: 'armani',
    location: { lat: 43.6535, lng: -79.3860 },
    distance: 0.6,
    openingHours: "Open 'til 7pm",
    isOpen: true,
    waitTime: 50,
    capacity: 50,
  },
  {
    id: '7',
    name: 'Converse',
    logo: 'converse',
    location: { lat: 43.6520, lng: -79.3800 },
    distance: 0.8,
    openingHours: "Closed",
    isOpen: false,
    waitTime: 0,
    capacity: 0,
  },
];

export const dummyPOIs: POI[] = [
  {
    id: 'poi1',
    name: 'Sanyuu West',
    category: 'eat',
    icon: '🍣',
    iconColor: 'bg-green-500',
    location: { lat: 43.6545, lng: -79.3845 },
    description: 'omakase sushi',
    isLiked: true,
    likedBy: 'weber',
  },
  {
    id: 'poi2',
    name: "People's",
    category: 'bar',
    icon: '🍺',
    iconColor: 'bg-purple-500',
    location: { lat: 43.6530, lng: -79.3825 },
    description: 'lowkey bar',
  },
  {
    id: 'poi3',
    name: 'Tacos 1986 West Village',
    category: 'eat',
    icon: '🌮',
    iconColor: 'bg-green-500',
    location: { lat: 43.6525, lng: -79.3810 },
    description: 'taco joint',
    isSaved: true,
  },
  {
    id: 'poi4',
    name: 'Bánh Anh Em',
    category: 'eat',
    icon: '🍜',
    iconColor: 'bg-orange-500',
    location: { lat: 43.6515, lng: -79.3830 },
    description: 'trending modern vietnamese',
  },
  {
    id: 'poi5',
    name: 'EIM Khao Mun Kai',
    category: 'eat',
    icon: '🍗',
    iconColor: 'bg-green-500',
    location: { lat: 43.6505, lng: -79.3820 },
    description: 'new hainanese chicken',
  },
  {
    id: 'poi6',
    name: 'Al-Andalus',
    category: 'bar',
    icon: '🍷',
    iconColor: 'bg-red-500',
    location: { lat: 43.6535, lng: -79.3850 },
    description: 'new mediterranean wine bar',
  },
  {
    id: 'poi7',
    name: 'Jing Fong',
    category: 'eat',
    icon: '🥟',
    iconColor: 'bg-green-500',
    location: { lat: 43.6520, lng: -79.3805 },
    description: 'dim sum carts',
    isSaved: true,
    savedBy: 'xōjoyce',
  },
  {
    id: 'poi8',
    name: 'Fishs Eddy',
    category: 'shop',
    icon: '🛍️',
    iconColor: 'bg-white',
    location: { lat: 43.6540, lng: -79.3835 },
    description: 'trending kitchenware',
  },
  {
    id: 'poi9',
    name: 'No Standing NYC',
    category: 'shop',
    icon: '👜',
    iconColor: 'bg-purple-500',
    location: { lat: 43.6510, lng: -79.3840 },
    description: 'lowkey vintage designer',
  },
  {
    id: 'poi10',
    name: 'The Jane Hotel',
    category: 'hotel',
    icon: '🏨',
    iconColor: 'bg-blue-500',
    location: { lat: 43.6530, lng: -79.3860 },
    description: 'nautical hotel',
  },
  {
    id: 'poi11',
    name: 'Apartment 5',
    category: 'club',
    icon: '🎉',
    iconColor: 'bg-gray-500',
    location: { lat: 43.6500, lng: -79.3815 },
    description: 'rsvp for the party',
  },
  {
    id: 'poi12',
    name: 'Downtown Music Gallery',
    category: 'entertainment',
    icon: '🎵',
    iconColor: 'bg-gray-500',
    location: { lat: 43.6525, lng: -79.3855 },
    description: 'jazz & experimental vinyl',
  },
];

export const TORONTO_CENTER_LOCATION = TORONTO_CENTER;

